# Generated by Django 3.2.9 on 2021-11-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_Name', models.CharField(default='software_name', max_length=150, verbose_name='اسم نرم افزار')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی ')),
            ],
            options={
                'verbose_name': 'نرم افزار',
                'verbose_name_plural': 'نرم افزار ها',
            },
        ),
    ]
