# Generated by Django 3.2.9 on 2021-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_compare_evaluate_metric_metricvalue_question_questionanswer_rank_softwareevaluate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'software', 'verbose_name_plural': 'softwares'},
        ),
        migrations.AlterField(
            model_name='rank',
            name='rankValue',
            field=models.IntegerField(),
        ),
    ]
