# Generated by Django 3.2.9 on 2021-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211203_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('producer', 'Producer'), ('avaluator', 'Avaluator')], default='admin', max_length=100),
        ),
    ]
