# Generated by Django 3.2.9 on 2021-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareevaluate',
            name='evaluate',
        ),
        migrations.AddField(
            model_name='metric',
            name='role',
            field=models.CharField(choices=[('category1', 'Category1'), ('category2', 'Category2'), ('category3', 'Category3')], default='category1', max_length=100),
        ),
        migrations.AddField(
            model_name='softwareevaluate',
            name='role',
            field=models.CharField(choices=[('metric', 'Metric'), ('questionnaire', 'Questionnaire'), ('poll', 'Poll'), ('rating', 'Rating')], default='metric', max_length=100),
        ),
        migrations.DeleteModel(
            name='Evaluate',
        ),
    ]
