# Generated by Django 3.2.9 on 2021-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211204_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='role',
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_class',
            field=models.CharField(choices=[('دسته 1', 'Category1'), ('دسته 2', 'Category2'), ('دسته 3', 'Category3')], default='category1', max_length=100),
        ),
    ]
