# Generated by Django 3.2.9 on 2021-12-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211204_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='metric_class',
            field=models.CharField(choices=[('category1', 'Category1'), ('category2', 'Category2'), ('category3', 'Category3')], default='category1', max_length=100),
        ),
    ]
