# Generated by Django 3.2.9 on 2021-12-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_metric_metric_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareevaluate',
            old_name='role',
            new_name='evaluate',
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_class',
            field=models.CharField(choices=[('category1', 'دسته 1'), ('category2', 'دسته 2'), ('category3', 'دسته 3')], default='category1', max_length=100),
        ),
    ]
