# Generated by Django 3.2.9 on 2021-12-05 14:17

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_metric_metric_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('file', stdimage.models.StdImageField(blank=True, upload_to='uploads/%y/%m/%d')),
            ],
        ),
    ]
