# Generated by Django 3.2.9 on 2021-12-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
