# Generated by Django 3.2.9 on 2021-12-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
    ]
