# Generated by Django 3.2.9 on 2021-12-05 15:58

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_software_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('file', models.FileField(upload_to='documents/%y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=stdimage.models.StdImageField(blank=True, upload_to='images/%y/%m/%d'),
        ),
    ]
