# Generated by Django 3.2.9 on 2021-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211205_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareevaluate',
            name='people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
