# Generated by Django 3.2.9 on 2021-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_softwareevaluate_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareevaluate',
            name='people',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
