# Generated by Django 3.2.9 on 2021-12-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_software_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareevaluate',
            name='evaluate',
        ),
        migrations.AddField(
            model_name='softwareevaluate',
            name='metric_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.metric'),
        ),
    ]
