# Generated by Django 3.2.9 on 2021-12-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211208_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
