# Generated by Django 3.2.9 on 2021-12-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_metric_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionResult',
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questionClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
