# Generated by Django 3.2.9 on 2021-12-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20211210_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareevaluate',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.software'),
        ),
        migrations.CreateModel(
            name='MetricEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metric_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.metric')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwareEvaluates', to='main.software')),
            ],
        ),
    ]
