# Generated by Django 3.2.9 on 2021-12-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20211210_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricevaluate',
            name='metric_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
