# Generated by Django 3.2.9 on 2021-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_metricevaluate_metric_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('producer', 'Producer'), ('superadmin', 'Super Admin'), ('avaluator', 'Avaluator')], default='admin', max_length=100),
        ),
    ]
