# Generated by Django 3.2.9 on 2021-12-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='user',
        ),
    ]
