# Generated by Django 3.2.9 on 2021-12-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_software_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricvalue',
            name='softwareEvaluate',
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='metricEvaluate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metricValues2', to='main.metricevaluate'),
        ),
    ]
