# Generated by Django 3.2.9 on 2021-12-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20211213_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='cat_id',
            new_name='Categorymetric',
        ),
    ]
