# Generated by Django 3.2.9 on 2021-12-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_cat_id_metric_categorymetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='Categorymetric',
            new_name='categorymetric',
        ),
    ]
