# Generated by Django 3.2.9 on 2021-12-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_categorymetric_metric_categorymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricevaluate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
