# Generated by Django 3.2.9 on 2021-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_metricevaluate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricevaluate',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
