# Generated by Django 3.2.9 on 2021-12-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_metricevaluate_created_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareevaluate',
            old_name='software',
            new_name='name',
        ),
    ]
