# Generated by Django 3.2.9 on 2021-12-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_software_softwareevaluate_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='software_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='softwareevaluate',
            old_name='name',
            new_name='software',
        ),
    ]
