# Generated by Django 3.2.9 on 2021-12-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20211215_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='name',
            new_name='software_name',
        ),
    ]
