# Generated by Django 3.2.9 on 2021-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_name_software_software_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='softwareEvaluate',
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answerValue',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'Very Good'), ('good', 'Good'), ('medium', 'Medium'), ('bad', 'Bad')], default='admin', max_length=100),
        ),
    ]
