# Generated by Django 3.2.9 on 2021-12-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20211216_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pepole', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answerValue',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'Very Good'), ('good', 'Good'), ('medium', 'Medium'), ('bad', 'Bad')], default='admin', max_length=100),
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.AddField(
            model_name='questionevaluate',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionAnswers2', to='main.question'),
        ),
        migrations.AddField(
            model_name='questionevaluate',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.software'),
        ),
    ]
