# Generated by Django 3.2.9 on 2021-12-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211216_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionevaluate',
            old_name='question',
            new_name='select_category',
        ),
    ]
