# Generated by Django 3.2.9 on 2021-12-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_software_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='user',
        ),
    ]
