# Generated by Django 3.2.9 on 2021-12-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_rename_user_software_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='added_by',
            new_name='user',
        ),
    ]
