# Generated by Django 3.2.9 on 2021-12-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_rename_added_by_software_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='user',
            new_name='added_by',
        ),
    ]
