# Generated by Django 3.2.9 on 2021-12-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_added_by_software_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='created_by',
        ),
    ]
