# Generated by Django 3.2.9 on 2021-12-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_software_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='user',
            field=models.OneToOneField(blank=True, default='main.User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
