# Generated by Django 3.2.9 on 2021-12-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_software_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='user',
        ),
        migrations.AddField(
            model_name='software',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
