# Generated by Django 3.2.9 on 2021-12-20 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20211220_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricevaluate',
            name='user',
        ),
        migrations.AddField(
            model_name='metricevaluate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
