# Generated by Django 3.2.9 on 2021-12-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_softwareevaluate_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareevaluate',
            old_name='people',
            new_name='thepeople',
        ),
    ]
