# Generated by Django 3.2.9 on 2021-12-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20211220_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='image',
        ),
    ]
