# Generated by Django 3.2.9 on 2021-12-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_software_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_image', to='main.image'),
        ),
    ]
