# Generated by Django 3.2.9 on 2021-12-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_software_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionevaluate',
            old_name='pepole',
            new_name='people',
        ),
    ]
