# Generated by Django 3.2.9 on 2021-12-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_questionevaluate_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionevaluate',
            name='pepole',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
