# Generated by Django 3.2.9 on 2021-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_questionevaluate_pepole'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionevaluate',
            name='people',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
