# Generated by Django 3.2.9 on 2021-12-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_questionevaluate_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionevaluate',
            old_name='people',
            new_name='pepole',
        ),
    ]
