# Generated by Django 3.2.9 on 2021-12-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_rename_pepole_questionevaluate_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionEvaluate',
        ),
    ]
