# Generated by Django 3.2.9 on 2021-12-26 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_delete_questionevaluate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('select_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionAnswers2', to='main.category')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.software')),
            ],
        ),
    ]
