# Generated by Django 3.2.9 on 2021-12-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_questionevaluate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی ')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answerValue',
        ),
        migrations.AlterField(
            model_name='question',
            name='questionClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categoryquestion'),
        ),
        migrations.AlterField(
            model_name='questionevaluate',
            name='select_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionAnswers2', to='main.categoryquestion'),
        ),
    ]
