# Generated by Django 3.2.9 on 2021-12-26 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20211226_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentText',
            new_name='textComment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='softwareEvaluate',
        ),
        migrations.CreateModel(
            name='CommentEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentText', models.CharField(blank=True, max_length=1000)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.software')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='CommentEvaluate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.commentevaluate'),
        ),
    ]
