# Generated by Django 3.2.9 on 2021-12-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20211227_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentevaluate',
            name='commentText',
        ),
    ]
