# Generated by Django 3.2.9 on 2021-12-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_rename_commentevaluate_comment_commentevaluate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='compareResult',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='softwareEvaluate',
        ),
        migrations.AddField(
            model_name='compare',
            name='people',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compare',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.software'),
        ),
        migrations.CreateModel(
            name='CompareResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compareResult', models.CharField(blank=True, max_length=256)),
                ('compare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.compare')),
            ],
        ),
    ]
