# Generated by Django 3.2.9 on 2021-12-29 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20211229_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compare',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
