# Generated by Django 3.2.9 on 2021-12-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20211229_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
