# Generated by Django 3.2.9 on 2022-01-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_metricvalue_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentevaluate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='metricevaluate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rankevaluate',
            options={'ordering': ['-id']},
        ),
    ]
