# Generated by Django 3.2.9 on 2022-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20220102_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionevaluate',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
