# Generated by Django 3.2.9 on 2022-01-04 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_questionevaluate_created_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metricValues', to='main.question')),
                ('questionEvaluate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionEvaluate', to='main.questionevaluate')),
            ],
        ),
    ]
