# Generated by Django 3.2.9 on 2022-01-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_questionvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvalue',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='QuestionValue', to='main.question'),
        ),
        migrations.AlterField(
            model_name='questionvalue',
            name='questionEvaluate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionEvaluate2', to='main.questionevaluate'),
        ),
        migrations.AlterField(
            model_name='questionvalue',
            name='value',
            field=models.CharField(choices=[('VS', 'خیلی کم'), ('S', 'کم'), ('M', 'متوسط'), ('G', 'خوب'), ('VG', 'بسیار خوب')], max_length=2),
        ),
    ]
