# Generated by Django 3.2.9 on 2022-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20220104_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvalue',
            name='value',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'Very Good'), ('good', 'Good'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=10),
        ),
    ]
