# Generated by Django 3.2.9 on 2022-01-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_alter_questionvalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software', to='main.software'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='software_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_2', to='main.software'),
        ),
    ]
