# Generated by Django 3.2.9 on 2022-01-04 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20220104_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=256)),
                ('compare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.compare')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CompareResult',
        ),
    ]
