# Generated by Django 3.2.9 on 2022-01-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20220104_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionevaluate',
            name='isEvaluated',
            field=models.BooleanField(default=False),
        ),
    ]
