# Generated by Django 3.2.9 on 2022-01-12 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_questionevaluate_isevaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionevaluate',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
