# Generated by Django 3.2.9 on 2022-01-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_questionevaluate_evaluated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionevaluate',
            name='evaluated_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
