# Generated by Django 3.2.9 on 2022-02-03 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_questionevaluate_evaluated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankevaluate',
            name='evaluated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankevaluate',
            name='isEvaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rankvalue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rankvalue',
            name='rankValue',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
