# Generated by Django 3.2.9 on 2022-02-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20220203_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankevaluate',
            options={},
        ),
    ]
