# Generated by Django 3.2.9 on 2022-02-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_alter_rankevaluate_options'),
    ]

    sql = """CREATE VIEW v_stats AS
    select a.Id, a.id as quesEvaluateid, b.select_category_id as category_id, 
    d.id as softwareid, d.software_name, c.id as questionid, c.questionText as Question, 
    (e.first_name || ' ' || e.last_name) AS 'evaluatedby', e.id as evaluatedby_id, a.value
    from main_questionvalue a 
    inner join main_questionevaluate b on a.questionEvaluate_id = b.id 
    inner join main_question c on a.question_id = c.id 
    inner join main_software d on b.software_id = d.id 
    inner join main_user e on a.created_by_id = e.id 
    where b.isEvaluated = 1 order by d.software_name;"""

    operations = [
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quesEvaluateid', models.IntegerField(blank=True, null=True)),
                ('softwareid', models.IntegerField(blank=True, null=True)),
                ('questionid', models.IntegerField(blank=True, null=True)),
                ('evaluatedby_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('software_name', models.CharField(max_length=254)),
                ('Question', models.CharField(max_length=254)),
                ('evaluatedby', models.CharField(max_length=254)),
                ('value', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'db_table': 'v_stats',
                'ordering': ['software_name'],
                'managed': False,
            },
        ),
    ]

    sql = """CREATE VIEW c_stats AS
    select a.Id, a.id as comEvaluateid, d.id as softwareid, d.software_name, 
    (e.first_name || ' ' || e.last_name) AS 'evaluatedby', a.textComment
    from main_Comment a 
    inner join main_CommentEvaluate b on a.commentEvaluate_id = b.id 
    inner join main_software d on b.software_id = d.id 
    inner join main_user e on a.created_by_id = e.id 
    where b.isEvaluated = 1 order by d.software_name;"""

    operations = [
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name='StatsC',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('comEvaluateid', models.IntegerField(blank=True, null=True)),
                ('softwareid', models.IntegerField(blank=True, null=True)),
                ('software_name', models.CharField(max_length=254)),
                ('evaluatedby', models.CharField(max_length=254)),
                ('textComment', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'StatC',
                'verbose_name_plural': 'StatsC',
                'db_table': 'c_stats',
                'ordering': ['software_name'],
                'managed': False,
            },
        ),
    ]
