# Generated by Django 3.2.9 on 2022-02-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20220207_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentevaluate',
            name='evaluated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentevaluate',
            name='isEvaluated',
            field=models.BooleanField(default=False),
        ),
    ]
