# Generated by Django 3.2.9 on 2022-02-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20220207_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparevalue',
            old_name='value',
            new_name='nameSoft',
        ),
        migrations.AddField(
            model_name='compare',
            name='evaluated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compare',
            name='isEvaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comparevalue',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.software'),
        ),
    ]
