# Generated by Django 3.2.9 on 2022-02-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20220207_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesEvaluateid', models.IntegerField(blank=True, null=True)),
                ('softwareid', models.IntegerField(blank=True, null=True)),
                ('questionid', models.IntegerField(blank=True, null=True)),
                ('software_name', models.CharField(max_length=254)),
                ('Question', models.CharField(max_length=254)),
                ('evaluatedby', models.CharField(max_length=254)),
                ('value', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'db_table': 'v_stats',
                'ordering': ['software_name'],
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='statsc',
            table='c_stats',
        ),
    ]
