# Generated by Django 3.2.9 on 2022-02-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_delete_statsc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparevalue',
            options={'ordering': ['software']},
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
