# Generated by Django 3.2.9 on 2022-02-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_comment_software'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankvalue',
            old_name='rankEvaluat',
            new_name='rankEvaluate',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='software',
        ),
    ]
