# Generated by Django 3.2.9 on 2022-02-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_auto_20220212_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankvalue',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.software'),
        ),
    ]
