# Generated by Django 3.2.9 on 2022-02-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_remove_rankvalue_software'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-id']},
        ),
    ]
