# Generated by Django 3.2.9 on 2022-04-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_metricevaluatedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricEvaluateDetails',
        ),
    ]
