# Generated by Django 3.2.9 on 2022-04-26 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_delete_metricevaluatedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEvaluateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selectedMetrics', to='main.metric')),
                ('metricEvaluate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selectedMetricEvaluate', to='main.metricevaluate')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
