# Generated by Django 3.2.9 on 2022-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_metricevaluatedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricevaluatedetails',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
