# Generated by Django 3.2.9 on 2022-04-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_metricevaluatedetails_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricevaluatedetails',
            name='value',
        ),
    ]
