# Generated by Django 3.2.9 on 2022-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_remove_metricevaluatedetails_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicationarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(blank=True, max_length=254, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی ')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=254, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی ')),
            ],
        ),
    ]
