# Generated by Django 3.2.9 on 2022-06-02 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_applicationarea_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=254, null=True)),
                ('istemplate', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی ')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.commentevaluate')),
                ('compare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.compare')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metricEvaluate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.metricevaluate')),
                ('questionEvaluate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.questionevaluate')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rankevaluate')),
            ],
        ),
    ]
