# Generated by Django 3.2.9 on 2022-06-03 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
