# Generated by Django 3.2.9 on 2022-06-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_alter_degree_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.commentevaluate'),
        ),
        migrations.AlterField(
            model_name='package',
            name='compare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.compare'),
        ),
        migrations.AlterField(
            model_name='package',
            name='metricEvaluate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.metricevaluate'),
        ),
        migrations.AlterField(
            model_name='package',
            name='questionEvaluate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.questionevaluate'),
        ),
        migrations.AlterField(
            model_name='package',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rankevaluate'),
        ),
    ]
