# Generated by Django 4.0.5 on 2022-07-29 05:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_notification_finish_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('email', 'by Email'), ('sms', 'by Sms')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='notification_finish_evaluation',
            field=models.CharField(blank=True, choices=[('email', 'by Email'), ('sms', 'by Sms')], max_length=512, null=True),
        ),
    ]
