# Generated by Django 4.0.5 on 2022-07-29 05:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='choices',
        ),
        migrations.AlterField(
            model_name='account',
            name='notification_finish_evaluation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('email', 'by Email'), ('sms', 'by Sms')], max_length=9, null=True, verbose_name='Finish evaluation'),
        ),
    ]
