# Generated by Django 4.0.5 on 2022-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_account_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
