# Generated by Django 4.0.5 on 2022-12-07 19:47

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_account_documents_account_document1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default=authentication.models.generateToken, max_length=20),
        ),
    ]
