# Generated by Django 4.0.5 on 2022-12-24 10:55

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_account_can_publish_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(default=authentication.models.generateToken, max_length=20, unique=True),
        ),
    ]
