# Generated by Django 4.0.5 on 2023-02-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_account_bio_account_evaluator_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_level',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3')], default='level2', max_length=100),
        ),
    ]
