# Generated by Django 4.0.5 on 2023-02-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_evaluation', '0002_alter_commentevaluate_completed_datetime_and_more'),
        ('comment_reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment_evaluation.commentevaluateresult'),
        ),
    ]
