# Generated by Django 4.0.5 on 2022-07-29 05:27

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('file', models.FileField(upload_to='documents/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('file', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='images/%y/%m/%d', variations={'large': (600, 400), 'medium': (300, 200), 'thumbnail': (100, 100, True)})),
            ],
        ),
    ]
