# Generated by Django 4.0.5 on 2022-08-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='evaluationDays',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
