# Generated by Django 4.0.5 on 2022-12-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_setting_evaluation_score_setting_initial_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='peopleneed_score',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
