# Generated by Django 4.0.5 on 2023-02-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_setting_peopleneed_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='comment_score_ratio',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='setting',
            name='compare_score_ratio',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='setting',
            name='metric_score_ratio',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setting',
            name='questionnaire_score_ratio',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='setting',
            name='rating_score_ratio',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
