# Generated by Django 4.0.5 on 2022-07-30 07:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='evaluations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('metric', 'Metric'), ('comment', 'Comment'), ('rating', 'Rating'), ('compare', 'Compare'), ('questionnaire', 'Questionnaire')], max_length=43, null=True, verbose_name='Evaluation'),
        ),
    ]
